import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { Item } from '@prisma/client';
import { Loading, Container } from '@nextui-org/react';
import { Layout } from '../components/Layout';
import { SignedOutView } from '../components/SignedOutView';
import { SignedInView } from '../components/SignedInView';

function Home({ items }: { items: Item[] }) {
  const { data: session, status } = useSession();

  // if status is loading, return a centered loading spinner
  if (status === 'loading') {
    return (
      <Container
        alignItems="center"
        css={{
          position: 'relative',
          height: 'calc(84vh - 76px)',
          '@xsMax': {
            height: 'calc(100vh - 64px)',
          },
        }}
        display="flex"
        gap={0}
        justify="center"
        wrap="nowrap"
      >
        <Loading size="lg" color={'secondary'} />
      </Container>
    );
  }
  return (
    <Layout>
      <Head>
        <title>Gearlist – Camera Database and Collection Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session ? <SignedOutView /> : <SignedInView />}
    </Layout>
  );
}

export default Home;
